### ISSUE TITLE
Example issues on a mac

### ISSUE THREAD

**Issue by schneems** [b-k/21st-Century-Examples#3]
First of all thanks for your book. I'm really liking it. I'm running through your examples using a mac, and there's a number of small mis-matches for example

```
$ make
C99 -g -O0 -Wall -I/opt/X11/include   stddev_bugged.c   -o stddev_bugged
c99: invalid argument `all' to -W
make: *** [stddev_bugged] Error 64
```

I've been able to get through most of them, like in this example just not using `-Wall`, but some examples are harder. Sometimes i'm not sure if it's a platform thing or just my user error. Is it useful/helpful for me to document any of these, or would it be noise to you?

**Comment by schneems** [comment]
Realized this is more of an issue with the difference between GCC/clang on a mac

```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

**Comment by ghost** [comment]
@b-k Have you had a chance to read this?
@schneems How did you fix this?

**Comment by schneems** [comment]
@bucaran you don't need `-Wall` in this example.

**Comment by ghost** [comment]
Great. Thanks @schneems

**Comment by b-k** [comment]
Hi, sorry I missed your message.

Some Macs ship with a version of GCC that has been recompiled to default to certain standards and use different flags from the usual gcc. On the Mac I tested on that had this gcc alias, I set up a one-line script name gcc consisting of
clang $*
and put that in my PATH. There are other ways to get around Apple's specialized gcc. For the examples, you can remove -Wall, as @schneems noted, but that's probably a bad habit for day-to-day code writing.

Also, I'm told that a lot of macs don't yet have the at_quick_exit function as specified in the C11 standard, so that will have to be commented out to compile on those macs. 

I hope that helps.

**Comment by randyzwitch** [comment]
I'm not able to get this working, same error as @schneems. I've tried the `clang $*` trick in a file named `gcc` in my root directory, and `chmod +x` it and put `~/` on my PATH, but I'm still getting error 64.

Is there something else that I'm missing? The code runs fine on Ubuntu, but that's not as convenient as using OSX on my Mac.

**Comment by randyzwitch** [comment]
So I got it working...at least for me, the minimal `makefile` is just the following, no need for alternate files/PATH solutions:

``` P=erf
OBJECTS=
CFLAGS= -g -Wall -O3
LDLIBS=
CC=clang

$(P): $(OBJECTS)
```

**Comment by ghost** [comment]
Great, thanks for posting this @randyzwitch

**Comment by schneems** [comment]
Can confirm. That worked, thanks!
